API_KEY = "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"
ENDPOINT = "https://openrouter.ai/api/v1/chat/completions"

MODELS = {
    "deepseek/deepseek-chat-v3-0324": "deepseek/deepseek-chat-v3-0324:free",
    "deepseek/deepseek-r1": "deepseek/deepseek-r1:free",
    "google/gemini-2.0-flash-exp": "google/gemini-2.0-flash-exp:free",
    "openrouter/optimus-alpha": "openrouter/optimus-alpha",
    "deepseek/deepseek-v3-base": "deepseek/deepseek-v3-base:free",
    "deepseek/deepseek-r1-zero": "deepseek/deepseek-r1-zero:free",
    "qwen/qwq-32b": "qwen/qwq-32b:free",
    "google/gemini-2.0-flash-thinking-exp-1219": "google/gemini-2.0-flash-thinking-exp-1219:free",
    "google/gemma-3-27b-it": "google/gemma-3-27b-it:free",
    "deepseek/deepseek-r1-distill-llama-70b": "deepseek/deepseek-r1-distill-llama-70b:free",
    "qwen/qwen2.5-vl-72b-instruct": "qwen/qwen2.5-vl-72b-instruct:free",
    "nvidia/llama-3.1-nemotron-ultra-253b-v1": "nvidia/llama-3.1-nemotron-ultra-253b-v1:free",
    "nvidia/llama-3.1-nemotron-70b-instruct": "nvidia/llama-3.1-nemotron-70b-instruct:free",
    "qwen/qwen-2.5-coder-32b-instruct": "qwen/qwen-2.5-coder-32b-instruct:free",
    "meta-llama/llama-3.3-70b-instruct": "meta-llama/llama-3.3-70b-instruct:free",
    "deepseek/deepseek-r1-distill-qwen-32b": "deepseek/deepseek-r1-distill-qwen-32b:free",
    "mistralai/mistral-nemo": "mistralai/mistral-nemo:free",
    "qwen/qwen-2.5-72b-instruct": "qwen/qwen-2.5-72b-instruct:free",
    "google/learnlm-1.5-pro-experimental": "google/learnlm-1.5-pro-experimental:free",
    "google/gemma-3-12b-it": "google/gemma-3-12b-it:free",
    "qwen/qwen2.5-vl-32b-instruct": "qwen/qwen2.5-vl-32b-instruct:free",
    "google/gemma-2-9b-it": "google/gemma-2-9b-it:free",
    "google/gemma-3-4b-it": "google/gemma-3-4b-it:free",
    "nvidia/llama-3.3-nemotron-super-49b-v1": "nvidia/llama-3.3-nemotron-super-49b-v1:free",
    "meta-llama/llama-3.1-8b-instruct": "meta-llama/llama-3.1-8b-instruct:free",
    "google/gemini-flash-1.5-8b-exp": "google/gemini-flash-1.5-8b-exp",
    "sophosympatheia/rogue-rose-103b-v0.2": "sophosympatheia/rogue-rose-103b-v0.2:free",
    "cognitivecomputations/dolphin3.0-mistral-24b": "cognitivecomputations/dolphin3.0-mistral-24b:free",
    "qwen/qwen2.5-vl-3b-instruct": "qwen/qwen2.5-vl-3b-instruct:free",
    "mistralai/mistral-7b-instruct": "mistralai/mistral-7b-instruct:free",
    "meta-llama/llama-3.2-11b-vision-instruct": "meta-llama/llama-3.2-11b-vision-instruct:free",
    "open-r1/olympiccoder-32b": "open-r1/olympiccoder-32b:free",
    "nousresearch/deephermes-3-llama-3-8b-preview": "nousresearch/deephermes-3-llama-3-8b-preview:free",
    "cognitivecomputations/dolphin3.0-r1-mistral-24b": "cognitivecomputations/dolphin3.0-r1-mistral-24b:free",
    "deepseek/deepseek-r1-distill-qwen-14b": "deepseek/deepseek-r1-distill-qwen-14b:free",
    "rekaai/reka-flash-3": "rekaai/reka-flash-3:free",
    "moonshotai/kimi-vl-a3b-thinking": "moonshotai/kimi-vl-a3b-thinking:free",
    "bytedance-research/ui-tars-72b": "bytedance-research/ui-tars-72b:free",
    "meta-llama/llama-3.2-3b-instruct": "meta-llama/llama-3.2-3b-instruct:free",
    "mistralai/mistral-small-24b-instruct-2501": "mistralai/mistral-small-24b-instruct-2501:free",
    "nvidia/llama-3.1-nemotron-nano-8b-v1": "nvidia/llama-3.1-nemotron-nano-8b-v1:free",
    "qwen/qwen-2.5-7b-instruct": "qwen/qwen-2.5-7b-instruct:free",
    "featherless/qwerky-72b": "featherless/qwerky-72b:free",
    "google/gemma-3-1b-it": "google/gemma-3-1b-it:free",
    "meta-llama/llama-3.2-1b-instruct": "meta-llama/llama-3.2-1b-instruct:free",
}

HEADERS = {
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json",
}
